---
abstract: 'Easy SQLite deployment'
author:
  - 'Robert Krimen <rkrimen@cpan.org>'
build_requires:
  Directory::Scratch: 0
  ExtUtils::MakeMaker: 6.42
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-SQLite-Deploy
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp::Clan::Share: 0
  DBD::SQLite: 0
  Moose: 0
  SQL::Script: 0
  Template: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/robertkrimen/DBIx-SQLite-Deploy/tree/master
version: 0.010
